version: '3.8'

services:
  seldom-platform:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - DB_TYPE=sqlite
      - DB_PATH=/app/data/seldom.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加前端服务
  # frontend:
  #   build: ../frontendv3
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - seldom-platform
  #   restart: unless-stopped

volumes:
  data:
  logs: